### ISSUE TITLE
Typealias with generic right-hand side overlaps self

### ISSUE THREAD

**Issue by a2** [SwiftDocOrg/swift-doc#137]
A `typealias` to a generic right-hand side overlaps itself as shown here:

<img width="862" alt="Screen Shot 2020-07-02 at 1 25 15 PM" src="https://user-images.githubusercontent.com/241156/86392031-c242cd80-bc68-11ea-9466-e7fd0624f640.png">

I think it has to do with this CSS rule:

```css
.highlight {
    text-indent: -2em;
}
```
