### ISSUE TITLE
fatal: could not read Password for 'https://***@github.com': No such device or address

### ISSUE THREAD

**Issue by WowbaggersLiquidLunch** [SwiftDocOrg/swift-doc#164]
I followed the GitHub Action in README, and wrote [this workflow](https://github.com/WowbaggersLiquidLunch/Interval/blob/15059279ba6f693961c60d162d7e064e408b8e0a/.github/workflows/publish%20new%20version.yml) for my repository:

```yaml
name: Publish New Version

on:
  release:
    types: [ published ]

jobs:
  update_wiki:
    name: Update Wiki
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Generate Documentation
        uses: SwiftDocOrg/swift-doc@master
        with:
          inputs: "./Sources"
          module-name: Interval
      - name: Upload Documentation to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

[Its latest log](https://github.com/WowbaggersLiquidLunch/Interval/runs/972723475?check_suite_focus=true) shows that it fails to update the documentation to the wiki page:

```
Initialized empty Git repository in /tmp/ci-XXXXJbcEHJ/.git/
From https://github.com/WowbaggersLiquidLunch/Interval.wiki
 * branch            HEAD       -> FETCH_HEAD
cp: can't stat '/README.md': No such file or directory
On branch master
nothing to commit, working tree clean
fatal: could not read Password for 'https://***@github.com': No such device or address
```

My workflow deviates from the README's only in 2 places: 
1. It uses `actions/checkout@v2` instead of `v1`.
2. It uses the default `secrets.GITHUB_TOKEN` instead a custom `secrets.GH_PERSONAL_ACCESS_TOKEN`.

Judging from the error message, I assume it might have something to do with the access token? If this is the case, what permissions should I give to the token for the GitHub action to work properly?
