### ISSUE TITLE
Github Action Consistently breaks

### ISSUE THREAD

**Issue by ApplebaumIan** [SwiftDocOrg/swift-doc#83]
So 1. Thank you @mattt for all of your help on Twitter! My documentation looks amazing now! 
I'm not totally sure if my issue is related to #78 as we were discussing. It's very difficult for me to diagnose because it instantly fails 
<img width="1506" alt="Screen Shot 2020-04-16 at 10 01 41 PM" src="https://user-images.githubusercontent.com/9451941/79524189-dbef5400-802d-11ea-915e-574826cc2db3.png">

Ignore the fact that I'm using the Action from my fork because the error persists when I use `swiftDocOrg/swift-doc@master`

I'm wondering if there is anyway I could find a more comprehensive error log to see if this is in fact related to #78?

**Comment by ApplebaumIan** [comment]
My yaml in case you need it! 
```yaml
name: Document Code
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Generate Documentation
        uses: Applebaumian/swift-doc@master # I'm using my fork but the error happens on swiftDocOrg/swift-doc@master as well.
        with:
          inputs: "ImageClassification"
          module-name: iASL
          format: "html"
          output: "Documentation"
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: Documentation # The folder the action should deploy.
#       - name: Upload Documentation to Wiki
#         uses: SwiftDocOrg/github-wiki-publish-action@v1
#         with:
#           path: ".build/documentation"
#         env:
#           GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

```

**Comment by mattt** [comment]
Hey @ApplebaumIan, can you please provide a link to the failed action on GitHub (assuming it's public)?

To get more logging information, [add a secret named `ACTIONS_RUNNER_DEBUG` with a value of `true`](https://help.github.com/en/actions/configuring-and-managing-workflows/managing-a-workflow-run#enabling-debug-logging).

**Comment by ApplebaumIan** [comment]
Here you go!
https://github.com/Capstone-Projects-2020-Spring/iASL-iOS/runs/594181504?check_suite_focus=true

**Comment by MattKiazyk** [comment]
@mattt latest master as of today, now successfully builds inside the action 💥  Guessing the #140 fixes the issue. 

@ApplebaumIan might want to try latest master to see if this fixes it.

**Comment by ApplebaumIan** [comment]
> @mattt latest master as of today, now successfully builds inside the action 💥  Guessing the #140 fixes the issue. 
> 
> 
> 
> @ApplebaumIan might want to try latest master to see if this fixes it. 

I'll make sure to give it a try thanks!

**Comment by stephencelis** [comment]
I've gotten things working but had to insert this step between the swift-doc action and the Github Pages action:

```yml
      - name: Update Permissions
        run: 'sudo chown --recursive $USER Documentation'
```

The output from the swift-doc action seems to have incorrect permissions.

**Comment by MattKiazyk** [comment]
I think that will hopefully be fixed in https://github.com/SwiftDocOrg/swift-doc/pull/146 

I get the same permission issue.

**Comment by mattt** [comment]
#146 is now merged. @ApplebaumIan Please let me know if you're still seeing this issue.

**Comment by ApplebaumIan** [comment]
I'm sorry I'm taking so long to get back to you all! Last week of summer university physics course... I'll definitely check this out next week!

**Comment by ApplebaumIan** [comment]
So on the bright side Swift-Doc does not crash! 🥳  
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/9451941/89695765-2188a300-d8e3-11ea-94f9-3b167f8ad577.png">
Not sure what the warnings are though. Also is there any documentation for how to publish the HTML documentation to gh-pages?

**Comment by mattt** [comment]
@ApplebaumIan 

> Not sure what the warnings are though. 

You're getting those warnings because you don't have GraphViz installed on your CI runner. You need to add a step that runs `brew install graphviz`.

> Something else to note is when I run swift-doc on my local machine I don't receive these GraphViz warnings!

That's probably because installing `swift-doc` via Homebrew automatically installs GraphViz as a dependency. Same for the `swift-doc` GitHub Action, which comes with everything needed. 

Because you're building from source with your own fork, you have to install GraphViz yourself.

> Also is there any documentation for how to publish the HTML documentation to gh-pages?

You can use an action [like this one](https://github.com/marketplace/actions/github-pages-action) to publish the generated content to your `gh-pages` branch.

**Comment by stephencelis** [comment]
@mattt As a heads-up it looks like I still need to run `chown` on the output to deploy it to GH pages.

**Comment by ApplebaumIan** [comment]
For whatever reason the swift-doc GitHub action keeps saying there are no `public` API Symbols in my project... now there isn't much `public` in our app but there definitely isn't zero. 

<img width="1440" alt="Screen Shot 2020-08-11 at 5 55 57 PM" src="https://user-images.githubusercontent.com/9451941/89952822-eb596500-dbfb-11ea-8748-7ff271738eb7.png">
Not sure what to make of it really... Also tried using the main swift-doc action instead of my fork and got the same results.

**Comment by mattt** [comment]
@ApplebaumIan Your workflow is missing a checkout step:

```yml
- name: Checkout
   uses: actions/checkout@v1
```

What it's doing right now is building `swift-doc` from source and running it in an otherwise empty directory.

**Comment by ApplebaumIan** [comment]
> @ApplebaumIan Your workflow is missing a checkout step:
> 
> ```yaml
> - name: Checkout
>    uses: actions/checkout@v1
> ```
> 
> What it's doing right now is building `swift-doc` from source and running it in an otherwise empty directory.

Huh, it makes sense that it wouldn't work without the checkout step... however after adding the suggested checkout step I'm getting the same result... https://github.com/Capstone-Projects-2020-Spring/iASL-iOS/blob/master/.github/workflows/document.yml

**Comment by mattt** [comment]
@ApplebaumIan The error message appears to be correct. Looking in the ImageClassification directory, there aren't any top-level symbols declared with a `public` access level.

**Comment by ApplebaumIan** [comment]
Yup turns out that it works with my fork and @stephencelis suggestion of using `chown` was required to deploy the pages! 🎉
Only hiccup is the stylesheet seems to be missing if you drill into a class! https://capstone-projects-2020-spring.github.io/iASL-iOS/ 
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/9451941/90067934-d80ece00-dcbd-11ea-9859-11432e2a054a.png">

**Comment by mattt** [comment]
@ApplebaumIan Glad to hear that's working for you. The reason why your CSS is broken is that you specified a base URL of `./`. You should instead use the destination URL of your site: `https://capstone-projects-2020-spring.github.io/iASL-iOS/`

**Comment by ApplebaumIan** [comment]
> You should instead use the destination URL of your site: `https://capstone-projects-2020-spring.github.io/iASL-iOS/`

That makes sense! Would this look like:
```yaml
- name: Generate Documentation
  uses: Applebaumian/swift-doc@master
  with:
    inputs: "ImageClassification"
    module-name: iASL
    format: "html"
    output: "Documentation"
    base-url: "https://capstone-projects-2020-spring.github.io/iASL-iOS/"
```
